name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
        GOPATH: ${{ github.workspace }}
        CDIR: ./src/github.com/${{ github.repository }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}

    - name: Install Dependencies
      run: |
        sudo apt-get install xorg-dev libgl1-mesa-dev
        go mod init
        go mod tidy
      working-directory: ${{ env.CDIR }}

    - name: Build
      run: go build -v .
      working-directory: ${{ env.CDIR }}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ${{ env.CDIR }}/orbbind
